using UnityEngine;
using System.Collections;
//including some .NET for dynamic arrays called List in C#
using System.Collections.Generic;

public class MovingObst : MonoBehaviour
{
	public GameObject target = null;
	// These weights will be exposed in the Inspector window
	public float avoidDist = 30.0f;

	// Each vehicle contains a CharacterController which
	// makes it easier to deal with the relationship between
	// movement initiated by the character and the forces
	// generated by contact with the terrain & other game objects.
	private CharacterController characterController = null;

	//reference to an array of obstacles
	//private  GameObject[] obstacles; 
	private Vector3 startPos;
	private Vector3 changeV3;
	public Vector3 extreme = new Vector3(2, 2, 2);

	public void Start()
	{
		characterController = gameObject.GetComponent<CharacterController>();
		startPos = transform.position;
		createV3();
	}

	public void createV3()
	{
		changeV3 = new Vector3(Random.Range(-extreme.x, extreme.x), Random.Range(-extreme.x, extreme.x), Random.Range(-extreme.x, extreme.x));
	}

	// Update is called once per frame
	public void Update()
	{
		transform.position = new Vector3(startPos.x + changeV3.x * Mathf.Sin(Time.time), startPos.y + changeV3.y * Mathf.Sin(Time.time), startPos.z + changeV3.x * Mathf.Sin(Time.time));
	}


}



